
const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCHED_CHATS";
const NEW_MESSAGE_ALERTS = "NEW_MESSAGE_ALERTS";
const NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEFT = "CHAT_LEFT";
const ONLINE_USERS = "ONLINE_USERS"
const UPDATE_ONLINE_STATUS = "UPDATE_ONLINE_STATUS";

const CALL_INITIATED = "CALL_INITIATED";
const REQUEST_CALL = "REQUEST_CALL";

const CALL_INCOMING = "CALL_INCOMING";
const CALL_INCOMING_RESPONSE = "CALL_INCOMING_RESPONSE";
const CALL_ENDED = "CALL_ENDED"
const RINGING = "RINGING";

const INITIATE_P2P = "INITIATE_P2P"
const INITIAL_OFFER = "INITIAL_OFFER";
const INITIAL_ANSWER = "INITIAL_ANSWER";
const SEND_ME_YOUR_STREAM = "SEND_ME_YOUR_STREAM"
const RENEGOTIATE_ANSWER = "RENEGOTIATE_ANSWER";
const RENEGOTIATE_OFFER = "RENEGOTIATE_OFFER";

const END_CALL = "END_CALL";

const onlineUsersMongoIds = "onlineUsersMongoIds"

module.exports = { ALERT, REFETCH_CHATS, NEW_MESSAGE_ALERTS, NEW_FRIEND_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING, CHAT_JOINED, CHAT_LEFT, ONLINE_USERS, UPDATE_ONLINE_STATUS, CALL_INITIATED, CALL_INCOMING, CALL_INCOMING_RESPONSE, CALL_ENDED, INITIAL_OFFER, INITIAL_ANSWER, INITIATE_P2P, RENEGOTIATE_OFFER, RENEGOTIATE_ANSWER, END_CALL, REQUEST_CALL, onlineUsersMongoIds, RINGING, SEND_ME_YOUR_STREAM };
