

const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCHED_CHATS";
const NEW_MESSAGE_ALERTS = "NEW_MESSAGE_ALERTS";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE"; // when message is of same chat that is opened
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEFT = "CHAT_LEFT"
const ONLINE_USERS = "ONLINE_USERS"

module.exports = { ALERT, REFETCH_CHATS, NEW_MESSAGE_ALERTS, NEW_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING, CHAT_JOINED, CHAT_LEFT, ONLINE_USERS };