

const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCHED_CHATS";
const NEW_MESSAGE_ALERTS = "NEW_MESSAGE_ALERTS";
const NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE"; // when message is of same chat that is opened
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const CHAT_JOINED = "CHAT_JOINED";
const UPDATE_ONLINE_STATUS = "UPDATE_ONLINE_STATUS";
const CHAT_LEFT = "CHAT_LEFT";
const ONLINE_USERS = "ONLINE_USERS";


const CALL_INCOMING = "CALL_INCOMING";
const RINGING = "RINGING";
const CALL_INCOMING_RESPONSE = "CALL_INCOMING_RESPONSE";
const CALL_ENDED = "CALL_ENDED";

const INITIAL_OFFER = "INITIAL_OFFER";
const INITIAL_ANSWER = "INITIAL_ANSWER";
const SEND_ME_YOUR_STREAM = "SEND_ME_YOUR_STREAM"
const HANDLE_ANSWERE = "HANDLE_ANSWERE";

const REQUEST_CALL = "REQUEST_CALL";
const INITIATE_P2P = "INITIATE_P2P"

const RENEGOTIATE_OFFER = "RENEGOTIATE_OFFER";
const RENEGOTIATE_ANSWER = "RENEGOTIATE_ANSWER"
const PEER_NEGO_DONE = "PEER_NEGO_DONE"
const PEER_NEGO_FINAL = "PEER_NEGO_FINAL";
const END_CALL = "END_CALL";

module.exports = { ALERT, REFETCH_CHATS, NEW_MESSAGE_ALERTS, NEW_FRIEND_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING, CHAT_JOINED, UPDATE_ONLINE_STATUS, CHAT_LEFT, ONLINE_USERS, CALL_INCOMING, CALL_INCOMING_RESPONSE, CALL_ENDED, INITIAL_OFFER, INITIAL_ANSWER, HANDLE_ANSWERE, INITIATE_P2P, SEND_ME_YOUR_STREAM, RENEGOTIATE_OFFER, RENEGOTIATE_ANSWER, PEER_NEGO_DONE, PEER_NEGO_FINAL, END_CALL, REQUEST_CALL, RINGING };