const RABBIT_MQ_EXCHANGE = "header_exchange";
const RABBIT_MQ_EXCHANGE_TYPE = "headers"

const REDIS_ONLINE_USERS_ID_MAPPED_WITH_SOCKET_ID = "onlineUsersSocketId"

module.exports = { RABBIT_MQ_EXCHANGE, RABBIT_MQ_EXCHANGE_TYPE, REDIS_ONLINE_USERS_ID_MAPPED_WITH_SOCKET_ID }