const RABBIT_MQ_EXCHANGE = "header_exchange";
const RABBIT_MQ_EXCHANGE_TYPE = "headers"

const REDIS_ONLINE_USERS_ID_MAPPED_WITH_SOCKET_ID = "onlineUsersSocketId"

const KAFKA_TOPIC_PUSH_NOTIFICATION = "push-notification";

module.exports = { RABBIT_MQ_EXCHANGE, RABBIT_MQ_EXCHANGE_TYPE, REDIS_ONLINE_USERS_ID_MAPPED_WITH_SOCKET_ID, KAFKA_TOPIC_PUSH_NOTIFICATION }