

const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCHED_CHATS";
const NEW_MESSAGE_ALERTS = "NEW_MESSAGE_ALERTS";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";


module.exports = { ALERT, REFETCH_CHATS, NEW_MESSAGE_ALERTS, NEW_REQUEST, NEW_MESSAGE };