

const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCHED_CHATS";
const NEW_MESSAGE_ALERTS = "NEW_MESSAGE_ALERTS";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";


module.exports = { ALERT, REFETCH_CHATS, NEW_MESSAGE_ALERTS, NEW_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING };